#!/usr/bin/env node
// tools/progress-report.mjs
// Read manifest + ingest logs + translation audit → overwrite _meta/progress-report.md
// with a dashboard snapshot.

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import minimist from 'minimist';
import { readManifest } from './lib/manifest.mjs';
import { vaultPath } from './lib/paths.mjs';

const argv = minimist(process.argv.slice(2), {
  boolean: ['verbose', 'help'],
  string: ['logs'],
  default: { logs: path.join(os.tmpdir(), 'ingest-logs') },
  alias: { h: 'help', v: 'verbose' },
});

if (argv.help) {
  console.error('progress-report.mjs [--logs DIR] [--verbose]');
  process.exit(0);
}

const REPORT_PATH = vaultPath('_meta/progress-report.md');

function tallyByWorker(rows) {
  const acc = {};
  for (const r of rows) {
    const w = r.assignedTo || 'unassigned';
    if (!acc[w]) acc[w] = { total: 0, pending: 0, 'in-progress': 0, 'needs-review': 0, done: 0, error: 0, skipped: 0 };
    acc[w].total += 1;
    if (acc[w][r.status] !== undefined) acc[w][r.status] += 1;
  }
  return acc;
}

function listLogFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  const walk = (d) => {
    const entries = fs.readdirSync(d, { withFileTypes: true });
    for (const e of entries) {
      const full = path.join(d, e.name);
      if (e.isDirectory()) walk(full);
      else if (e.isFile() && full.endsWith('.log')) {
        const st = fs.statSync(full);
        out.push({ path: full, size: st.size, mtimeMs: st.mtimeMs });
      }
    }
  };
  try { walk(dir); } catch {}
  return out.sort((a, b) => b.mtimeMs - a.mtimeMs);
}

function countTranslationRows() {
  try {
    const text = fs.readFileSync(vaultPath('_meta/translation-audit.md'), 'utf8');
    // Count audit rows (markdown table lines that start with "| 2" — ISO date).
    const m = text.match(/^\|\s*\d{4}-\d{2}-\d{2}/gm);
    return m ? m.length : 0;
  } catch {
    return 0;
  }
}

function countPendingMedia() {
  // Scan _raw/translations + /tmp/ingest-work for stub pages (status/pending-transcription).
  // _raw/translations is in the vault; /tmp paths are harder to enumerate, skip.
  let count = 0;
  const walk = (d) => {
    const entries = fs.readdirSync(d, { withFileTypes: true });
    for (const e of entries) {
      const full = path.join(d, e.name);
      if (e.isDirectory()) walk(full);
      else if (e.isFile() && full.endsWith('.md')) {
        try {
          const t = fs.readFileSync(full, 'utf8');
          if (/status\/pending-transcription/.test(t)) count += 1;
        } catch {}
      }
    }
  };
  try { walk(vaultPath('_raw/translations')); } catch {}
  return count;
}

function main() {
  const doc = readManifest();
  const byWorker = tallyByWorker(doc.rows);
  const logs = listLogFiles(argv.logs);
  const translationCount = countTranslationRows();
  const pendingMedia = countPendingMedia();

  const overall = doc.rows.reduce(
    (acc, r) => {
      acc.total += 1;
      acc[r.status] = (acc[r.status] || 0) + 1;
      return acc;
    },
    { total: 0 },
  );

  const lines = [];
  lines.push('---');
  lines.push('title: Progress Report — Mega Mind ingest');
  lines.push('type: meta');
  lines.push('tags: [wiki, progress, v2, phase-2]');
  lines.push(`generated_at: ${new Date().toISOString()}`);
  lines.push('---');
  lines.push('');
  lines.push('# Progress Report');
  lines.push('');
  lines.push(`Generated by \`tools/progress-report.mjs\`. Refresh with \`npm run progress\`.`);
  lines.push('');
  lines.push(`**Total manifest rows:** ${overall.total}`);
  lines.push(`**Translation calls logged:** ${translationCount}`);
  lines.push(`**Pending media (transcription):** ${pendingMedia}`);
  lines.push('');
  lines.push('## Overall');
  lines.push('');
  lines.push('| Status | Count |');
  lines.push('|---|---|');
  for (const [k, v] of Object.entries(overall).filter(([k]) => k !== 'total').sort()) {
    lines.push(`| ${k} | ${v} |`);
  }
  lines.push('');
  lines.push('## Per worker');
  lines.push('');
  lines.push('| Worker | Total | pending | in-progress | needs-review | done | error | skipped |');
  lines.push('|---|---|---|---|---|---|---|---|');
  const workers = Object.keys(byWorker).sort();
  for (const w of workers) {
    const b = byWorker[w];
    lines.push(`| ${w} | ${b.total} | ${b.pending} | ${b['in-progress']} | ${b['needs-review']} | ${b.done} | ${b.error} | ${b.skipped} |`);
  }
  lines.push('');
  lines.push('## Recent worker logs');
  lines.push('');
  if (logs.length === 0) {
    lines.push('_No log files found under_ `' + argv.logs + '`');
  } else {
    lines.push('| Log | Size | Last modified |');
    lines.push('|---|---|---|');
    for (const l of logs.slice(0, 20)) {
      const sizeKB = (l.size / 1024).toFixed(1);
      const when = new Date(l.mtimeMs).toISOString();
      lines.push(`| \`${l.path.replace(/\\/g, '/')}\` | ${sizeKB} KB | ${when} |`);
    }
  }
  lines.push('');

  fs.writeFileSync(REPORT_PATH, lines.join('\n'), 'utf8');
  console.log(`progress-report: wrote ${REPORT_PATH}`);
  console.log(`total=${overall.total}, done=${overall.done || 0}, in-progress=${overall['in-progress'] || 0}, pending=${overall.pending || 0}, translations=${translationCount}, pending-media=${pendingMedia}`);
}

try {
  main();
} catch (err) {
  console.error(`progress-report: ${err.message}`);
  process.exit(1);
}
